### ISSUE TITLE
Got UnsupportedClassVersionError when using vscode plugin

### ISSUE THREAD

**Issue by xingweitian** [eisopux/checker-framework-vscode#27]
I got an error when using the vscode plugin.
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/checkerframework/languageserver/ServerMain has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
[Error - 4:02:28 p.m.] Connection to server got closed. Server will not be restarted.
```

**Comment by zhangjiangqige** [comment]
Thanks for reporting. This is because the [last release of eisopux/checker-framework-languageserver](https://github.com/eisopux/checker-framework-languageserver/releases/tag/v0.1.1) that's downloaded automatically was compiled using java 9, and you were using java 8.

I've updated the release with a jar compiled with java 8; it should resolve this.

**Comment by xingweitian** [comment]
Yes, it works properly now. Thanks!
